### ISSUE TITLE
Turn off console logging if it is not required.

### ISSUE THREAD

**Issue by eugene-rozov** [mslosarz/nextrtc-js-client#2]
Right now when NextRTC client is started, a lot of debug logs are printed to console. For example, console.log('req: ', payload); (LOC 102)

It would be great to use a logging facade or to add a parameter in the configuration for disabling logs.

**Comment by mslosarz** [comment]
Good point! I'll do it soon, and publish new version

**Comment by mslosarz** [comment]
fixed in version 1.0.6 (I added flag debug with default value false)
